name: build java project with maven 

on: 
    push:
      branches:
        - main
    workflow_dispatch:    
 ### the above trigger causes the workflow to be triggered when code is poushed to main. 

jobs:

    Build-test-deploy: ### this specifies the job name 
        runs-on: ubuntu-latest ### this specifies where the job should run
        steps:
            - name: clone repository
              uses: actions/checkout@v3  ### the first step clones our repo into the runner. 

            - name: install and setup java with maven 
              uses: actions/setup-java@v3
              with:
                distribution: 'adopt'
                java-version: '11' 
            - name: code build with maven 
              run:  mvn package   

            - name: upload mvn artifact
              uses: actions/upload-artifact@v3
              with:
                name: webapp
                path: target/*.war
    deploy_artifact:
        runs-on: ubuntu-latest
        needs: Build-test-deploy
        steps:
          - name: clone repository
            uses: actions/checkout@v3  ### the first step clones our repo into the runner. 

          - name: install and setup java with maven 
            uses: actions/setup-java@v3
            with:
              distribution: 'adopt'
              java-version: '11'
          - name: artifact download
            uses: actions/download-artifact@v3
            with:
              name: webapp
              path: ~/
          - name: Set up Environment Variables
            run: |
              echo "SONARQUBE_USERNAME=${{ secrets.SONARQUBE_USERNAME }}" >> $GITHUB_ENV
              echo "SONARQUBE_PASSWORD=${{ secrets.SONARQUBE_PASSWORD }}" >> $GITHUB_ENV
          - name: Run SonarQube Analysis
            run: |
              mvn sonar:sonar \
                -Dsonar.login=$SONARQUBE_USERNAME \
                -Dsonar.password=$SONARQUBE_PASSWORD \
                -Dsonar.host.url=http://54.211.193.235:9000
          # - name: tomcat aspect 
          #   run: |
          #     echo ${{ secrets.TOMCAT_KP }} > ~/key.pem
          #     chmod 400 ~/key.pem
          # - name: see key in home directory
          #   run: ls -l ~/
          # - name: push to tomcat server
          #   run: sudo scp -i ~/key.pem -o StrictHostKeyChecking=no ~/*.war ec2-user@54.242.145.113:/opt/tomcat9/webapps
          